version: '3'
services:
  postgres:
    image: 'postgres:12'
    environment:
      POSTGRES_DB: fibbonaci_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fib_pass
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=fibbonaci_db
      - PGUSER=postgres
      - PGPASSWORD=fib_pass
    ports:
      - '5000:5000'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
